language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python update-attack.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: ./output/
  target-branch: master
  on:
    branch: build
